version: "3.9"

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    volumes:
      - etcd-data:/etcd-data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    depends_on:
      - etcd

volumes:
  etcd-data:
    driver: local
